name: Deploy to Production

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run Deployment Script on VPS
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          password: ${{ secrets.VPS_PASSWORD }}
          port: 22
          script: |
            cd api

            echo "→ Git pull..."
            git fetch origin
            git reset --hard origin/main

            echo "→ Installing dependencies and building the application..."
            npm install --force

            echo "→ Restarting the application with PM2..."
            pm2 restart api || pm2 start npm --name "api" -- start
            pm2 save
